site_name: Jnote Blog
repo_name: xiajihnu/jnote-blog
repo_url: https://github.com/xiajihnu/jnote-blog
site_url: https://jnote-blog.pages.dev
copyright: Fernando Celmer

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Components:
      - nav/components/sidebar.md
      - nav/components/top-menu.md
      - nav/components/preview.md
      - nav/components/footer.md
      - nav/components/site-name.md
      - nav/components/standard-title.md
    - Styles:
      - nav/styles/highlightjs.md
      - nav/styles/favicon.md
      - nav/styles/colors.md
      - nav/styles/logo.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md
    - 个人笔记:
      - nav/mynote/internet-access.md
      - nav/mynote/python-evn.md
      - nav/mynote/windows-tips.md

theme:
  name: simple-blog
  favicon: assets/favicon.ico
  logo: assets/logo.png
  theme_style: light
  site_name_style: bold
  title_style: bold
  sidebar: true
  navigation_depth: 2
  highlightjs: true
    - yaml
    - python
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: true

extra_javascript:
 - assets/custom.js